;/*FB_PKG_DELIM*/

__d("CometVideoHomeCommonEntryPointVariables",["WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={feedLocation:"VIDEO_HOME_FEED",isComet:!0,privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"video_home",scale:d("WebPixelRatio").get(),useDefaultActor:!1};g["default"]=a}),98);
__d("CometVideoHomeFeedEntryPointVariables",["CometVideoHomeCommonEntryPointVariables","gkx"],(function(a,b,c,d,e,f,g){"use strict";a=babelHelpers["extends"]({},c("CometVideoHomeCommonEntryPointVariables"),{aggregatedVIDs:[],caller:null,isLoggedOut:c("gkx")("22809"),isRelatedVideosQueryDeferred:!1,triggerData:{injected_video_id:null}});g["default"]=a}),98);
__d("CometVideoHomeFeedRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="31047986381466589"}),null);
__d("FBReels_enable_click_to_see_more_logging_gk.relayprovider",["gkx"],(function(a,b,c,d,e,f,g){"use strict";a={get:function(){return c("gkx")("11257")}};g["default"]=a}),98);
__d("CometVideoHomeFeedRootQuery$Parameters",["CometUFIShareActionMigration.relayprovider","CometVideoHomeFeedRootQuery_facebookRelayOperation","FBReelsIFUTileContent_reelsIFUPlayOnHover.relayprovider","FBReels_enable_click_to_see_more_logging_gk.relayprovider","FBReels_enable_view_dubbed_audio_type_gk.relayprovider","GHLShouldChangeAdIdFieldName.relayprovider","GHLShouldChangeSponsoredDataFieldName.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometVideoHomeFeedRootQuery_facebookRelayOperation"),metadata:{},name:"CometVideoHomeFeedRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__FBReelsIFUTileContent_reelsIFUPlayOnHoverrelayprovider:b("FBReelsIFUTileContent_reelsIFUPlayOnHover.relayprovider"),__relay_internal__pv__GHLShouldChangeAdIdFieldNamerelayprovider:b("GHLShouldChangeAdIdFieldName.relayprovider"),__relay_internal__pv__FBReels_enable_view_dubbed_audio_type_gkrelayprovider:b("FBReels_enable_view_dubbed_audio_type_gk.relayprovider"),__relay_internal__pv__CometUFIShareActionMigrationrelayprovider:b("CometUFIShareActionMigration.relayprovider"),__relay_internal__pv__FBReels_enable_click_to_see_more_logging_gkrelayprovider:b("FBReels_enable_click_to_see_more_logging_gk.relayprovider"),__relay_internal__pv__GHLShouldChangeSponsoredDataFieldNamerelayprovider:b("GHLShouldChangeSponsoredDataFieldName.relayprovider")}}};e.exports=a}),null);
__d("CometVideoHomeNewPermalinkHeroUnitQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="10055110934587040"}),null);
__d("CometVideoHomeRHCRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9348210221973750"}),null);
__d("CometVideoHomeSurfaceHighlightsWrapperQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9996282753766494"}),null);
__d("CometVideoHomeSurfaceHighlightsWrapperQuery$Parameters",["CometVideoHomeSurfaceHighlightsWrapperQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometVideoHomeSurfaceHighlightsWrapperQuery_facebookRelayOperation"),metadata:{},name:"CometVideoHomeSurfaceHighlightsWrapperQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("validateChainingCaller",[],(function(a,b,c,d,e,f){"use strict";function a(a){return typeof a==="string"?a:null}f["default"]=a}),66);